python test_hf.py \
	--data_names "gsm8k" \
	--output_dir "$SAVE_DIR" \
	--model_name_or_path meta-llama/Llama-3.2-1B-Instruct \
	--ckpt_dir bcywinski/no_cot_sft_llama1b_gsm8k-aug-nl \
	--seed 11 \
	--model_max_length 512 \
	--bf16 \
	--batch_size 128 \
	--greedy True \
	--inf_num_iterations 1
